- hosts: localhost
  gather_facts: false
  vars_files:
  - defaults.yml
  tasks:
  - name: Destroy installed cluster
    shell: "./openshift-install destroy cluster"
    args:
      chdir: "{{ path }}/bin"
